os: linux
arch: ppc64le
sudo: false
language: cpp
compiler:
  - g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-7
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
script:
  - make all
  - ./karatsuba
